### PR TITLE
aggressively remove directory that prevent linking packages

### LINKED ISSUE #15: yerna doesn't properly unlink an installed dependency in place of a symlink
The docs claim that [Yerna will remove anything in the way of a symlink](https://github.com/palantir/yerna#symlinks), but this only seems to work when there's a symlink in the way. If there's an installed package there (for instance), it'll just throw an exception instead.

### PR DESCRIPTION
**Pull request by despairblue**
fix #15

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/yerna](https://github.com/palantir/yerna), @despairblue! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by despairblue** [comment]
I couldn't update the yarn.lock file since it uses palantir's on premise npm registry. Also I could not run the tests:

```
> yernapkg@0.5.0 test /Users/despairblue/git/yerna
> tape 'test/**/*.js'

TAP version 13
# git root
ok 1 should be equal
# yerna.json root
ok 2 should be equal
# error if no git root or yerna.json
ok 3 Error: yerna: Can't find project root from /private/var/folders/pg/lqtf5xjj0qj8qr4bvtptvpf80000gn/T/tmp-69756BWk2frM2Mv6h. Looking for git repository, yerna.json, or lerna.json.
ok 4 should be truthy

1..4
# tests 4
# pass  4

# ok
```

**Comment by seansfkelley** [comment]
Whoops, never noticed the lockfile issue. Just pushed a commit to master to rewrite it to npmjs.org.

As for the tests -- they are indeed running correctly, though the error message being logged (an expected output from the test) is somewhat confusing. I also just pushed a commit to tweak the assertion to not log that message.

**Comment by seansfkelley** [comment]
I went to test this out and it works great, thanks! I actually ended up tweaking it (adding logging, mostly) and committing it as 182cd7dac184d9d51a8457f752d2c09df0811ccd, so I'm going to close this PR out.

**Comment by despairblue** [comment]
Awesome, thanks for making this and happy I could help a little :+1:

**Pull request closed without merging**
